### PR TITLE
[Edit Profile] Edit profile GNB subview

### PR DESCRIPTION
**Pull request by duckmoll**
- Overwrite local profile editing stored info
- Alert when empty fields
- Sync with Back End after back

Screen Shot 2019-06-20 at 1 42 07 AM

Video in slack

### CODE REVIEW

**Comment by tangziyi001** [comment]
Screen Shot 2019-06-20 at 9 16 43 PM

Should we adjust the font a bit?

**Comment by tangziyi001** [comment]
We might want to make the font a bit more polished like this: 
Screen Shot 2019-06-20 at 9 19 13 PM

**Comment by tangziyi001** [comment]
Also as a follow up, we might want to make those elements reusable across main page and edit profile page. Do you know if it is doable with nib?

**Comment by duckmoll** [comment]
> Screen Shot 2019-06-20 at 9 16 43 PM
> 
> Should we adjust the font a bit?

I'm thinking to make those fonts dynamic to fit different size characters.

**Comment by tangziyi001** [comment]
> I'm

Yeah agreed. At a starting point let's just use the zeplin version maybe? I'm not sure if we have enough time before test to make all fonts dynamic.

**Comment by duckmoll** [comment]
> Also as a follow up, we might want to make those elements reusable across main page and edit profile page. Do you know if it is doable with nib?

Yes. It is ideal to use dynamic table view cells.

**Comment by duckmoll** [comment]
> > I'm
> 
> Yeah agreed. At a starting point let's just use the zeplin version maybe? I'm not sure if we have enough time before test to make all fonts dynamic.

Yes. I will clean the UI as follow up.

**Pull request merged**
