### PR TITLE
Updated hometown page and new education page 

### PR DESCRIPTION
**Pull request by Kevinxu99**
Added back button to hometown profile page
Completed the new Education #198 

newHT
newEdu

### CODE REVIEW

**Comment by duckmoll** [comment]
It looks good! From your video in slack, it does not show the full keyboard. Is it because you did not include it in your screenshot, or you typed the text using laptop keyboard?

**Comment by Kevinxu99** [comment]
Keyboard doesn’t show up in the simulator. I typed everything on my laptop

**Comment by tangziyi001** [comment]
@Kevinxu99 In simulator, can you try "command+shift+k" and see if keyboard shows up?

**Comment by tangziyi001** [comment]
It seems that the distance between 学校 and 你已经获取的 is too close compared to Zeplin: https://app.zeplin.io/project/5cbfb4abddd6eb538f773ce9/screen/5cc007d4888a0b267835f44f. Can you slightly add more distance there?

**Comment by tangziyi001** [comment]
The conflict should be easy to resolve. Just remove the markers from the source code and keep both changes would be ok.

**Pull request merged**
